/**
 * @fileoverview 잔류농약 분석 항목 데이터
 * 출처: 잔류농약성분목록(LC,GC구분).xlsx
 * GC-MS/MS 258종 + LC-MS/MS 267종 = 전체 525종 (중복 포함 BOTH)
 *
 * method: GC = GC-MS/MS 전용, LC = LC-MS/MS 전용, BOTH = 양쪽 모두
 */

const PESTICIDE_ANALYSIS_DATA = [
    { engName: '2-phenyl phenol', method: 'GC' },
    { engName: '2,3,5-Trimethacarb', method: 'LC' },
    { engName: '2,4,6-trichlorophenol', method: 'GC' },
    { engName: '2.6-DIPN', method: 'GC' },
    { engName: '3-hydroxycarbofuran', method: 'LC' },
    { engName: '3,4,5-Trimethacarb', method: 'LC' },
    { engName: '6-Benzyl amiopurine', method: 'LC' },
    { engName: 'Abamectin B1a', method: 'LC' },
    { engName: 'Acephate', method: 'LC' },
    { engName: 'Acequinocyl', method: 'LC' },
    { engName: 'Acetamiprid', method: 'LC' },
    { engName: 'Acetochlor', method: 'GC' },
    { engName: 'Acibenzolar acid', method: 'LC' },
    { engName: 'Acibenzolar-S-methyl', method: 'LC' },
    { engName: 'Acrinathrin', method: 'GC' },
    { engName: 'Alachlor', method: 'GC' },
    { engName: 'Aldicarb', method: 'LC' },
    { engName: 'Aldrin', method: 'GC' },
    { engName: 'Allethrin', method: 'LC' },
    { engName: 'Allidochlor', method: 'GC' },
    { engName: 'Ametoctradin', method: 'LC' },
    { engName: 'Ametryn', method: 'GC' },
    { engName: 'Amisulbrom', method: 'LC' },
    { engName: 'Amitraz', method: 'LC' },
    { engName: 'Aramite', method: 'GC' },
    { engName: 'Aspon', method: 'GC' },
    { engName: 'Asulam', method: 'LC' },
    { engName: 'Atrazine', method: 'GC' },
    { engName: 'Azamethiphos', method: 'LC' },
    { engName: 'Azinphos-ethyl', method: 'GC' },
    { engName: 'Azinphos-methyl', method: 'LC' },
    { engName: 'Azoxystrobin', method: 'LC' },
    { engName: 'Benalaxyl', method: 'LC' },
    { engName: 'Bendiocarb', method: 'LC' },
    { engName: 'Benfluralin', method: 'GC' },
    { engName: 'Benodanil', method: 'GC' },
    { engName: 'Bensulide', method: 'LC' },
    { engName: 'Bentazone', method: 'LC' },
    { engName: 'Benthiavalicarb-isopropyl R', method: 'LC' },
    { engName: 'Benthiavalicarb-isopropyl S', method: 'LC' },
    { engName: 'Benzobicyclon', method: 'LC' },
    { engName: 'Benzoylprop-ethyl', method: 'GC' },
    { engName: 'BHC-α', method: 'GC' },
    { engName: 'BHC-β', method: 'GC' },
    { engName: 'BHC-δ', method: 'GC' },
    { engName: 'Bifenazate', method: 'GC' },
    { engName: 'Bifenthrin', method: 'GC' },
    { engName: 'BioResmethrin', method: 'LC' },
    { engName: 'Bispyribac-sodium', method: 'LC' },
    { engName: 'Bistrifluron', method: 'LC' },
    { engName: 'Bitertanol', method: 'LC' },
    { engName: 'Bixafen', method: 'LC' },
    { engName: 'Boscalid', method: 'GC' },
    { engName: 'Bromacil', method: 'LC' },
    { engName: 'Bromobutide', method: 'GC' },
    { engName: 'Bromophos-ethyl', method: 'GC' },
    { engName: 'Bromophos-methyl', method: 'GC' },
    { engName: 'Bromopropylate', method: 'GC' },
    { engName: 'BTS 44595', method: 'LC' },
    { engName: 'BTS 44596', method: 'LC' },
    { engName: 'Bupirimate', method: 'GC' },
    { engName: 'Buprofezin', method: 'GC' },
    { engName: 'Butachlor', method: 'GC' },
    { engName: 'Butocarboxim', method: 'LC' },
    { engName: 'Butralin', method: 'GC' },
    { engName: 'Butylate', method: 'GC' },
    { engName: 'Cadusafos', method: 'GC' },
    { engName: 'Carbaryl', method: 'LC' },
    { engName: 'Carbendazim', method: 'LC' },
    { engName: 'Carbetamide', method: 'LC' },
    { engName: 'Carbofuran', method: 'LC' },
    { engName: 'Carboxin', method: 'GC' },
    { engName: 'Carpropamide', method: 'LC' },
    { engName: 'Celthodim sulfone', method: 'LC' },
    { engName: 'Chinomethionat', method: 'GC' },
    { engName: 'Chloraneb', method: 'GC' },
    { engName: 'Chlorantraniliprole', method: 'LC' },
    { engName: 'Chlorbenside', method: 'GC' },
    { engName: 'Chlorbufam', method: 'GC' },
    { engName: 'Chlordane-cis', method: 'GC' },
    { engName: 'Chlordane-trans', method: 'GC' },
    { engName: 'Chlorethoxyfos', method: 'GC' },
    { engName: 'Chlorfenapyr', method: 'GC' },
    { engName: 'Chlorfenson', method: 'GC' },
    { engName: 'Chlorfenvinphos E', method: 'LC' },
    { engName: 'Chlorfenvinphos Z', method: 'LC' },
    { engName: 'Chlorfluazuron', method: 'LC' },
    { engName: 'Chlorflurenol-methyl', method: 'GC' },
    { engName: 'Chloridazone', method: 'LC' },
    { engName: 'Chlornitrofen', method: 'GC' },
    { engName: 'Chlorobenauron', method: 'LC' },
    { engName: 'Chlorobenzilate', method: 'GC' },
    { engName: 'Chloropropylate', method: 'GC' },
    { engName: 'Chlorothalonil', method: 'GC' },
    { engName: 'Chlorotoluron', method: 'LC' },
    { engName: 'Chloroxuron', method: 'LC' },
    { engName: 'Chlorpropham', method: 'GC' },
    { engName: 'Chlorpyrifos-methyl', method: 'GC' },
    { engName: 'Chlorpyrifos(-ethyl)', method: 'GC' },
    { engName: 'Chlorthal-dimethyl', method: 'GC' },
    { engName: 'Chlorthion', method: 'GC' },
    { engName: 'Chlorthiophos', method: 'GC' },
    { engName: 'Chlozolinate', method: 'GC' },
    { engName: 'Chromafenozide', method: 'LC' },
    { engName: 'Cinmethylin', method: 'GC' },
    { engName: 'Clethodim', method: 'LC' },
    { engName: 'Clethoim sulfoxide', method: 'LC' },
    { engName: 'Clofentezine', method: 'LC' },
    { engName: 'Clomeprop', method: 'LC' },
    { engName: 'Clothianidin', method: 'LC' },
    { engName: 'Coumaphos', method: 'GC' },
    { engName: 'Crotoxyphos', method: 'LC' },
    { engName: 'Crufomate', method: 'LC' },
    { engName: 'Cyanazine', method: 'LC' },
    { engName: 'Cyanophos', method: 'GC' },
    { engName: 'Cyantraniliprole', method: 'LC' },
    { engName: 'Cyazofamid', method: 'LC' },
    { engName: 'Cyclaniliprole', method: 'LC' },
    { engName: 'Cycloate', method: 'LC' },
    { engName: 'Cycloprothrin', method: 'LC' },
    { engName: 'Cyclosulfamuron', method: 'LC' },
    { engName: 'Cyenopyrafen', method: 'LC' },
    { engName: 'Cyflufenamid', method: 'GC' },
    { engName: 'Cyflumetofen', method: 'LC' },
    { engName: 'Cyfluthrin', method: 'GC' },
    { engName: 'Cyhalothrin-γ', method: 'GC' },
    { engName: 'Cyhalothrin-λ', method: 'GC' },
    { engName: 'Cymoxanil', method: 'LC' },
    { engName: 'Cypermethrin', method: 'GC' },
    { engName: 'Cyprazine', method: 'GC' },
    { engName: 'Cyprodinil', method: 'GC' },
    { engName: 'Cyprononazole', method: 'LC' },
    { engName: 'Cyromazine', method: 'LC' },
    { engName: 'DDD-pp', method: 'GC' },
    { engName: 'DDE-pp', method: 'GC' },
    { engName: 'DDT-op', method: 'GC' },
    { engName: 'DDT-pp', method: 'GC' },
    { engName: 'Deltamethrin', method: 'GC' },
    { engName: 'Demeton-S', method: 'LC' },
    { engName: 'Demeton-S-methyl', method: 'LC' },
    { engName: 'Demeton-S-methyl-sulfone', method: 'LC' },
    { engName: 'Demeton-S-sulfone', method: 'LC' },
    { engName: 'Demeton-S-sulfoxide', method: 'LC' },
    { engName: 'Desmetryn', method: 'GC' },
    { engName: 'Dialifor', method: 'GC' },
    { engName: 'Diallate', method: 'GC' },
    { engName: 'Diazinon', method: 'GC' },
    { engName: 'Dichlobenil', method: 'GC' },
    { engName: 'Dichlofenthion', method: 'GC' },
    { engName: 'Dichlofluanid', method: 'GC' },
    { engName: 'Dichlormid', method: 'GC' },
    { engName: 'Dichlorvos', method: 'LC' },
    { engName: 'Diclobutrazol', method: 'GC' },
    { engName: 'Diclosulam', method: 'LC' },
    { engName: 'Dicofol', method: 'GC' },
    { engName: 'Dicrotophos', method: 'GC' },
    { engName: 'Dieldrin', method: 'GC' },
    { engName: 'Diethatyl-ethyl', method: 'GC' },
    { engName: 'Diethofencarb', method: 'GC' },
    { engName: 'Difenoconazole', method: 'GC' },
    { engName: 'Diflubenzuron', method: 'LC' },
    { engName: 'Diflufenican', method: 'GC' },
    { engName: 'Dimethachlor', method: 'GC' },
    { engName: 'Dimethenamid', method: 'GC' },
    { engName: 'Dimethipin', method: 'GC' },
    { engName: 'Dimethoate', method: 'LC' },
    { engName: 'Dimethomorph E', method: 'GC' },
    { engName: 'Dimethomorph Z', method: 'GC' },
    { engName: 'Diniconazole', method: 'GC' },
    { engName: 'Dinitramine', method: 'GC' },
    { engName: 'Dinotefuran', method: 'LC' },
    { engName: 'Dioxathion', method: 'GC' },
    { engName: 'Diphenylamine', method: 'GC' },
    { engName: 'Disulfoton', method: 'LC' },
    { engName: 'Disulfoton sulfone', method: 'LC' },
    { engName: 'Disulfoton sulfoxide', method: 'LC' },
    { engName: 'Dithiopyr', method: 'GC' },
    { engName: 'Diuron', method: 'LC' },
    { engName: 'Dodine', method: 'LC' },
    { engName: 'Edifenphos', method: 'GC' },
    { engName: 'EMA', method: 'GC' },
    { engName: 'Emamectin B1a', method: 'LC' },
    { engName: 'Endosulfan sulfate', method: 'GC' },
    { engName: 'Endosulfan-α', method: 'GC' },
    { engName: 'Endosulfan-β', method: 'GC' },
    { engName: 'Endrin', method: 'GC' },
    { engName: 'Epoxiconazole', method: 'GC' },
    { engName: 'EPTC', method: 'GC' },
    { engName: 'Etaconazole', method: 'GC' },
    { engName: 'Ethaboxam', method: 'LC' },
    { engName: 'Ethalfluralin', method: 'GC' },
    { engName: 'Ethion', method: 'GC' },
    { engName: 'Ethofurnesate', method: 'GC' },
    { engName: 'Ethoprophos', method: 'GC' },
    { engName: 'Ethoxazole', method: 'GC' },
    { engName: 'Ethychlozate', method: 'GC' },
    { engName: 'Etofenprox', method: 'LC' },
    { engName: 'Etridiazole', method: 'GC' },
    { engName: 'Etrimfos', method: 'LC' },
    { engName: 'Famoxadone', method: 'LC' },
    { engName: 'Fenamidone', method: 'GC' },
    { engName: 'Fenarimol', method: 'GC' },
    { engName: 'Fenazaquin', method: 'LC' },
    { engName: 'Fenbuconazole', method: 'GC' },
    { engName: 'Fenchlorphos', method: 'GC' },
    { engName: 'Fenfuram', method: 'GC' },
    { engName: 'Fenhexamid', method: 'LC' },
    { engName: 'Fenitrothion', method: 'GC' },
    { engName: 'Fenobucarb', method: 'GC' },
    { engName: 'Fenpropathrin', method: 'GC' },
    { engName: 'Fenpropimorph', method: 'GC' },
    { engName: 'Fenpyrazamine', method: 'GC' },
    { engName: 'Fenpyroximate', method: 'LC' },
    { engName: 'Fenson', method: 'GC' },
    { engName: 'Fensulfothion', method: 'LC' },
    { engName: 'Fenthion', method: 'GC' },
    { engName: 'Fenvalerate', method: 'GC' },
    { engName: 'Ferimzone E', method: 'LC' },
    { engName: 'Ferimzone Z', method: 'LC' },
    { engName: 'Fipronil', method: 'GC' },
    { engName: 'Flamprop-isopropyl', method: 'GC' },
    { engName: 'Flazasulfuron', method: 'LC' },
    { engName: 'Flonicamid', method: 'LC' },
    { engName: 'Fluazifop-butyl', method: 'GC' },
    { engName: 'Fluazinam', method: 'LC' },
    { engName: 'Flubendiamide', method: 'LC' },
    { engName: 'Fluchloralin', method: 'GC' },
    { engName: 'Fludioxonil', method: 'LC' },
    { engName: 'Fluensulfone', method: 'GC' },
    { engName: 'Flufenoxuron', method: 'LC' },
    { engName: 'Flufenpyr-ethyl', method: 'GC' },
    { engName: 'Flumetralin', method: 'GC' },
    { engName: 'Fluometuron', method: 'LC' },
    { engName: 'Fluopicolide', method: 'LC' },
    { engName: 'Fluopyram', method: 'GC' },
    { engName: 'Fluorochloridone', method: 'GC' },
    { engName: 'Flupoxam', method: 'LC' },
    { engName: 'Flupyradifurone', method: 'LC' },
    { engName: 'Fluquinconazole', method: 'GC' },
    { engName: 'Fluridone', method: 'LC' },
    { engName: 'Flusilazole', method: 'GC' },
    { engName: 'Flusulfamide', method: 'LC' },
    { engName: 'Fluthiacet-methyl', method: 'LC' },
    { engName: 'Flutianil', method: 'GC' },
    { engName: 'Flutolanil', method: 'LC' },
    { engName: 'Flutriafol', method: 'LC' },
    { engName: 'Fluvalinate', method: 'GC' },
    { engName: 'Fluxametamide', method: 'LC' },
    { engName: 'Fluxapyroxad', method: 'GC' },
    { engName: 'Fnoxanil', method: 'GC' },
    { engName: 'Folpet', method: 'GC' },
    { engName: 'Fomesafen', method: 'LC' },
    { engName: 'Foramsulfuron', method: 'LC' },
    { engName: 'Formothion', method: 'GC' },
    { engName: 'Fosthiazte', method: 'LC' },
    { engName: 'Furathiocarb', method: 'LC' },
    { engName: 'Gibberellic acid', method: 'LC' },
    { engName: 'Halosulfuron-methyl', method: 'LC' },
    { engName: 'Haloxyfop', method: 'LC' },
    { engName: 'HEMA', method: 'GC' },
    { engName: 'Heptachlor', method: 'GC' },
    { engName: 'Heptachlor epoxide', method: 'GC' },
    { engName: 'Heptenophos', method: 'GC' },
    { engName: 'Hexachlorobenzene', method: 'GC' },
    { engName: 'Hexaconazole', method: 'LC' },
    { engName: 'Hexazinone', method: 'LC' },
    { engName: 'Hexythiazox', method: 'GC' },
    { engName: 'Imazalil', method: 'LC' },
    { engName: 'Imibenconazole', method: 'LC' },
    { engName: 'Imicyafos', method: 'LC' },
    { engName: 'Imidacloprid', method: 'LC' },
    { engName: 'Indaziflam', method: 'LC' },
    { engName: 'Indoxacarb', method: 'GC' },
    { engName: 'Ipconazole', method: 'GC' },
    { engName: 'Ipfencarbazone', method: 'LC' },
    { engName: 'Iprobenfos', method: 'GC' },
    { engName: 'Iprodione', method: 'GC' },
    { engName: 'Isofenphos', method: 'GC' },
    { engName: 'Isofenphos-methyl', method: 'GC' },
    { engName: 'Isoprocarb', method: 'GC' },
    { engName: 'Isopropalin', method: 'GC' },
    { engName: 'Isoprothiolane', method: 'GC' },
    { engName: 'Isoproturon', method: 'LC' },
    { engName: 'Isopyrazam', method: 'GC' },
    { engName: 'Isotianil', method: 'GC' },
    { engName: 'Isoxaben', method: 'LC' },
    { engName: 'Isoxadifen-ethyl', method: 'GC' },
    { engName: 'Isoxathion', method: 'LC' },
    { engName: 'KIE-9749', method: 'LC' },
    { engName: 'Kresoxim-methyl', method: 'GC' },
    { engName: 'Lemiectin A3', method: 'LC' },
    { engName: 'Lemiectin A4', method: 'LC' },
    { engName: 'Lenacil', method: 'LC' },
    { engName: 'Leptophos', method: 'GC' },
    { engName: 'Lindane(y-BHC)', method: 'GC' },
    { engName: 'Linuron', method: 'LC' },
    { engName: 'Lufenuron', method: 'LC' },
    { engName: 'Malaoxon', method: 'LC' },
    { engName: 'Malathion', method: 'LC' },
    { engName: 'Mandestrobin', method: 'LC' },
    { engName: 'Mandipropamid', method: 'LC' },
    { engName: 'Mecoprop-P', method: 'LC' },
    { engName: 'Mefenacet', method: 'LC' },
    { engName: 'Mefenpyr-diethyl', method: 'GC' },
    { engName: 'Mefentrifluconazole', method: 'LC' },
    { engName: 'Mephosfolan', method: 'LC' },
    { engName: 'Mesotrione', method: 'LC' },
    { engName: 'Metaflumizone E', method: 'LC' },
    { engName: 'Metaflumizone Z', method: 'LC' },
    { engName: 'Metalaxyl', method: 'GC' },
    { engName: 'Metamitron', method: 'LC' },
    { engName: 'Metconazole', method: 'LC' },
    { engName: 'Methabenzthiazuron', method: 'LC' },
    { engName: 'Methamidophos', method: 'LC' },
    { engName: 'Methidathion', method: 'GC' },
    { engName: 'Methiocarb', method: 'LC' },
    { engName: 'Methomyl', method: 'LC' },
    { engName: 'Methoprotryn', method: 'GC' },
    { engName: 'Methoxychlor', method: 'GC' },
    { engName: 'Methoxyfenozide', method: 'LC' },
    { engName: 'Methyl trithion', method: 'GC' },
    { engName: 'Metolachlor', method: 'GC' },
    { engName: 'Metominostrobin', method: 'LC' },
    { engName: 'Metrafenone', method: 'LC' },
    { engName: 'Metribuzin', method: 'GC' },
    { engName: 'Mevinphos', method: 'LC' },
    { engName: 'MGK-264', method: 'GC' },
    { engName: 'Milbemectin A3', method: 'LC' },
    { engName: 'Milbemectin A4', method: 'LC' },
    { engName: 'Monocrotophos', method: 'LC' },
    { engName: 'Monolinuron', method: 'GC' },
    { engName: 'Myclobutanil', method: 'GC' },
    { engName: 'Napropamide', method: 'LC' },
    { engName: 'Neburon', method: 'LC' },
    { engName: 'Nicosulfuron', method: 'LC' },
    { engName: 'Nitenpyram', method: 'LC' },
    { engName: 'Nitrapyrin', method: 'GC' },
    { engName: 'Nitrothal-siopropyl', method: 'GC' },
    { engName: 'Nonachlor-cis', method: 'GC' },
    { engName: 'Nonachlor-trans', method: 'GC' },
    { engName: 'Norea Noruron', method: 'LC' },
    { engName: 'Norflurazon', method: 'LC' },
    { engName: 'Novaluron', method: 'LC' },
    { engName: 'Nuarimol', method: 'GC' },
    { engName: 'Omethoate', method: 'LC' },
    { engName: 'Orthosulfamuron', method: 'LC' },
    { engName: 'Orysastrobin', method: 'LC' },
    { engName: 'Oryzalin', method: 'LC' },
    { engName: 'Oxacarboxin', method: 'LC' },
    { engName: 'Oxademeton-methyl', method: 'LC' },
    { engName: 'Oxadiargyl', method: 'LC' },
    { engName: 'Oxadiazon', method: 'GC' },
    { engName: 'Oxadixyl', method: 'GC' },
    { engName: 'Oxafluorfen', method: 'GC' },
    { engName: 'Oxamyl', method: 'LC' },
    { engName: 'Oxamyl oxime', method: 'LC' },
    { engName: 'Oxathiapiprolin', method: 'LC' },
    { engName: 'Paclobutrazol', method: 'GC' },
    { engName: 'Parathion', method: 'GC' },
    { engName: 'Parathion-methyl', method: 'GC' },
    { engName: 'Pebulate', method: 'LC' },
    { engName: 'Pencycuron', method: 'LC' },
    { engName: 'Pendimethalin', method: 'GC' },
    { engName: 'Penflufen', method: 'GC' },
    { engName: 'Pentachlorobenzonitrile', method: 'GC' },
    { engName: 'Penthiopyrad', method: 'GC' },
    { engName: 'Pentoxazone', method: 'GC' },
    { engName: 'Perhane', method: 'GC' },
    { engName: 'Permethrin-cis', method: 'GC' },
    { engName: 'Permethrin-trans', method: 'GC' },
    { engName: 'Phenmedipham', method: 'LC' },
    { engName: 'Phenothrin-cis', method: 'LC' },
    { engName: 'Phenothrin-trans', method: 'LC' },
    { engName: 'Phenthoate', method: 'GC' },
    { engName: 'Phorate', method: 'LC' },
    { engName: 'Phorate oxon', method: 'LC' },
    { engName: 'Phorate oxon sulfone', method: 'LC' },
    { engName: 'Phorate oxon sulfoxide', method: 'LC' },
    { engName: 'Phorate sulfone', method: 'LC' },
    { engName: 'Phorate sulfoxide', method: 'LC' },
    { engName: 'Phosalone', method: 'GC' },
    { engName: 'Phosfolan', method: 'LC' },
    { engName: 'Phosmet', method: 'GC' },
    { engName: 'Phosphamidon E', method: 'GC' },
    { engName: 'Phosphamidon Z', method: 'GC' },
    { engName: 'Phoxim', method: 'LC' },
    { engName: 'Phthalide, Fthalide', method: 'GC' },
    { engName: 'Picarbutrazox', method: 'LC' },
    { engName: 'Picolinafen', method: 'LC' },
    { engName: 'Picoxystrobin', method: 'GC' },
    { engName: 'Piperonyl butoxide', method: 'GC' },
    { engName: 'Pirimicarb', method: 'GC' },
    { engName: 'Pirimiphos-ethyl', method: 'GC' },
    { engName: 'Pirimiphos-methyl', method: 'GC' },
    { engName: 'Prochloraz', method: 'GC' },
    { engName: 'Procymidone', method: 'GC' },
    { engName: 'Prodiamine', method: 'GC' },
    { engName: 'Profenofos', method: 'GC' },
    { engName: 'Profluralin', method: 'GC' },
    { engName: 'Prohydrojasmon', method: 'GC' },
    { engName: 'Prometon', method: 'GC' },
    { engName: 'Propachlor', method: 'GC' },
    { engName: 'Propamocarb', method: 'LC' },
    { engName: 'Propanil', method: 'GC' },
    { engName: 'Propargite', method: 'LC' },
    { engName: 'Propetamphos', method: 'GC' },
    { engName: 'Propham', method: 'GC' },
    { engName: 'Propiconazole', method: 'GC' },
    { engName: 'Propisochlor', method: 'GC' },
    { engName: 'Propyrisulfuron', method: 'LC' },
    { engName: 'Proquinazid', method: 'LC' },
    { engName: 'Prosulfocarb', method: 'LC' },
    { engName: 'Prothiofos', method: 'GC' },
    { engName: 'Pyaziflumid', method: 'LC' },
    { engName: 'Pydiflumetofen', method: 'LC' },
    { engName: 'Pyflubumide', method: 'LC' },
    { engName: 'Pyflubumide-NH', method: 'LC' },
    { engName: 'Pymetrozine', method: 'LC' },
    { engName: 'Pyracarbolid', method: 'GC' },
    { engName: 'Pyraclofos', method: 'GC' },
    { engName: 'Pyraclonil', method: 'LC' },
    { engName: 'Pyraclostrobin', method: 'LC' },
    { engName: 'Pyraflufen-ethyl', method: 'GC' },
    { engName: 'Pyrazolate', method: 'LC' },
    { engName: 'Pyrazosulfuron-ethyl', method: 'LC' },
    { engName: 'Pyrazoxyfen', method: 'LC' },
    { engName: 'Pyribencarb', method: 'LC' },
    { engName: 'Pyridaben', method: 'LC' },
    { engName: 'Pyridalyl', method: 'GC' },
    { engName: 'Pyridaphenthion', method: 'LC' },
    { engName: 'Pyridate', method: 'LC' },
    { engName: 'Pyrifenox', method: 'GC' },
    { engName: 'Pyrifluquinazon', method: 'LC' },
    { engName: 'Pyrimethanil', method: 'GC' },
    { engName: 'Pyriofenone', method: 'LC' },
    { engName: 'Pyriproxyfen', method: 'LC' },
    { engName: 'Quinalphos', method: 'GC' },
    { engName: 'Quinoxyfen', method: 'GC' },
    { engName: 'Quintozene', method: 'GC' },
    { engName: 'Saflufenacil', method: 'LC' },
    { engName: 'Secbumeton', method: 'LC' },
    { engName: 'Sedaxane-cis', method: 'LC' },
    { engName: 'Sedaxane-trans', method: 'LC' },
    { engName: 'Sethoxydim', method: 'LC' },
    { engName: 'Silafluofen', method: 'GC' },
    { engName: 'Simazine', method: 'LC' },
    { engName: 'Simeconazole', method: 'GC' },
    { engName: 'Spinetoram', method: 'LC' },
    { engName: 'Spinosyn A', method: 'LC' },
    { engName: 'Spinosyn D', method: 'LC' },
    { engName: 'Spirodiclofen', method: 'LC' },
    { engName: 'Spiromesifen', method: 'GC' },
    { engName: 'Spirotetramat', method: 'LC' },
    { engName: 'Spirotetramat-enol', method: 'LC' },
    { engName: 'Spiroxamine', method: 'GC' },
    { engName: 'Sulfentrazone', method: 'LC' },
    { engName: 'Sulfotep', method: 'GC' },
    { engName: 'Sulfoxaflor', method: 'LC' },
    { engName: 'Sulprofos', method: 'LC' },
    { engName: 'Tebuconazole', method: 'GC' },
    { engName: 'Tebufenozide', method: 'LC' },
    { engName: 'Tebufenpyrad', method: 'GC' },
    { engName: 'Tebufloquin', method: 'LC' },
    { engName: 'Tebufloquin M1', method: 'LC' },
    { engName: 'Tebupirimfos', method: 'GC' },
    { engName: 'Tebuthiuron', method: 'LC' },
    { engName: 'Tecnazene', method: 'GC' },
    { engName: 'Teflubenzuron', method: 'LC' },
    { engName: 'Tefluthrin', method: 'GC' },
    { engName: 'Tepraloxydim', method: 'LC' },
    { engName: 'Terbacil', method: 'GC' },
    { engName: 'Terbufos', method: 'LC' },
    { engName: 'Terbufos oxon', method: 'LC' },
    { engName: 'Terbufos oxon sulfone', method: 'LC' },
    { engName: 'Terbufos oxon sulfoxide', method: 'LC' },
    { engName: 'Terbufos sulfone', method: 'LC' },
    { engName: 'Terbufos sulfoxide', method: 'LC' },
    { engName: 'Terbumeton', method: 'GC' },
    { engName: 'Tetrachlorvinphos', method: 'GC' },
    { engName: 'Tetraconazole', method: 'GC' },
    { engName: 'Tetradifon', method: 'GC' },
    { engName: 'Tetramethrin', method: 'GC' },
    { engName: 'Tetraniliprole', method: 'LC' },
    { engName: 'Thiabendazole', method: 'LC' },
    { engName: 'Thiacloprid', method: 'LC' },
    { engName: 'Thiamethoxam', method: 'LC' },
    { engName: 'Thidiazuron', method: 'LC' },
    { engName: 'Thifluzamide', method: 'GC' },
    { engName: 'Thiobencarb', method: 'LC' },
    { engName: 'Thiodicarb', method: 'LC' },
    { engName: 'Thiometon', method: 'GC' },
    { engName: 'Thionazin', method: 'GC' },
    { engName: 'Thiophanate-methyl', method: 'LC' },
    { engName: 'Tiadinil', method: 'LC' },
    { engName: 'Tolclofos-methyl', method: 'GC' },
    { engName: 'Tolfenpyrad', method: 'LC' },
    { engName: 'Tralomethrin', method: 'GC' },
    { engName: 'Triadimefon', method: 'GC' },
    { engName: 'Triadimenol', method: 'GC' },
    { engName: 'Triafamone', method: 'LC' },
    { engName: 'Triazamate', method: 'LC' },
    { engName: 'Triazophos', method: 'GC' },
    { engName: 'Tribufos', method: 'LC' },
    { engName: 'Trichlorfon', method: 'LC' },
    { engName: 'Triclopyr', method: 'LC' },
    { engName: 'Tricyclazole', method: 'LC' },
    { engName: 'Tridiphane', method: 'GC' },
    { engName: 'Trifloxystrobin', method: 'GC' },
    { engName: 'Trifloxysulfuron', method: 'LC' },
    { engName: 'Triflumizole', method: 'GC' },
    { engName: 'Triflumuron', method: 'LC' },
    { engName: 'Trifluralin', method: 'GC' },
    { engName: 'Triforine', method: 'LC' },
    { engName: 'Trinexapac', method: 'LC' },
    { engName: 'Trinexapac-ethyl', method: 'LC' },
    { engName: 'Triticonazole', method: 'LC' },
    { engName: 'TZ1-E', method: 'LC' },
    { engName: 'Uniconazole', method: 'LC' },
    { engName: 'Valifenalate', method: 'LC' },
    { engName: 'Vernolate', method: 'LC' },
    { engName: 'Vinclozolin', method: 'GC' },
    { engName: 'XMC', method: 'LC' },
    { engName: 'Zoxamide', method: 'GC' },
    { engName: 'δ-keto-Endrin', method: 'GC' },
    { engName: 'ΕΡΝ', method: 'GC' },
];

window.PESTICIDE_ANALYSIS_DATA = PESTICIDE_ANALYSIS_DATA;

window.getPesticidesByMethod = function(method) {
    if (method === 'all') return PESTICIDE_ANALYSIS_DATA;
    if (method === 'GC') return PESTICIDE_ANALYSIS_DATA.filter(p => p.method === 'GC' || p.method === 'BOTH');
    if (method === 'LC') return PESTICIDE_ANALYSIS_DATA.filter(p => p.method === 'LC' || p.method === 'BOTH');
    return PESTICIDE_ANALYSIS_DATA.filter(p => p.method === method);
};

window.searchPesticides = function(query, method, limit) {
    method = method || 'all';
    limit = limit || 20;
    if (!query || query.length < 1) return [];
    var q = query.toLowerCase();
    var pool = method === 'all' ? PESTICIDE_ANALYSIS_DATA : window.getPesticidesByMethod(method);
    return pool.filter(function(p) { return p.engName.toLowerCase().includes(q); }).slice(0, limit);
};

/**
 * 정성 분석 항목 (464종 분석체계 중 정성 항목)
 * 다성분 40종 기준이나 DDT/Cyhalothrin 등 하위 변종 포함하여 52 + 단성분 6 = 58 엔트리
 */
const QUALITATIVE_PESTICIDES = new Set([
    // 다성분 40종 (525종 데이터와 이름 일치시킴)
    'Abamectin B1a', 'Acequinocyl', 'BioResmethrin', 'Bispyribac-sodium',
    'Bitertanol', 'Carbofuran', '3-hydroxycarbofuran', 'Furathiocarb',
    'Foramsulfuron', 'Gibberellic acid', 'Haloxyfop', 'Lepimectin',
    'Mecoprop-P', 'Methomyl', 'Thiodicarb', 'Nicosulfuron', 'Novaluron',
    'Propargite', 'Pyridate', 'Pyriproxyfen', 'Spirotetramat-enol',
    'Tefuryltrione', 'Triclopyr', 'Triforine', 'Tetramethrin',
    '2.6-DIPN', 'Acetochlor', 'EMA', 'HEMA',
    'Acrinathrin', 'Chinomethionat', 'Chlorothalonil', 'Cyfluthrin',
    'Cyhalothrin-γ', 'Cyhalothrin-λ', 'Cypermethrin',
    'DDT-op', 'DDT-pp', 'DDD-pp', 'DDE-pp',
    'Dimethipin', 'Dimethomorph E', 'Dimethomorph Z', 'Edifenphos', 'Fenvalerate',
    'Fluvalinate', 'Iprodione', '2-phenyl phenol',
    'Prochloraz', '2,4,6-trichlorophenol', 'Acibenzolar acid',
    // 단성분 6종
    'Amitraz', 'Cyromazine', 'Dichlofluanid', 'Folpet',
    'Pymetrozine', 'Trinexapac-ethyl'
]);
window.QUALITATIVE_PESTICIDES = QUALITATIVE_PESTICIDES;

/**
 * 정성 분석 항목인지 확인
 * @param {string} name - 농약 영문명
 * @returns {boolean}
 */
window.isQualitativePesticide = function(name) {
    if (!name) return false;
    return QUALITATIVE_PESTICIDES.has(name);
};

window.getPesticideStats = function() {
    var gcOnly = PESTICIDE_ANALYSIS_DATA.filter(function(p) { return p.method === 'GC'; }).length;
    var lcOnly = PESTICIDE_ANALYSIS_DATA.filter(function(p) { return p.method === 'LC'; }).length;
    var both = PESTICIDE_ANALYSIS_DATA.filter(function(p) { return p.method === 'BOTH'; }).length;
    return { total: PESTICIDE_ANALYSIS_DATA.length, gc: gcOnly + both, lc: lcOnly + both, gcOnly: gcOnly, lcOnly: lcOnly, both: both };
};
